[project]
name = "aws-bedrock"
version = "0.1.0"
description = "A AWS Bedrock se concentra em AI Generative"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
]
